x_depart: 1
y_depart: 0.2
angle_depart: 1.57
use_odom: true
trajectory_goal_error: 0.1

trajectoires:
   - [[1, 0.5, 0.2], [1, 0.5, 0.7], [-1, 1, 0.7], [-1, 1, 0.2]] # square
   - [[1, 0.5, 0.2], [1, 0.75, 0.7], [-1, 1, 0.2]] # triangle
