/**:
  ros__parameters:
    navigation_hub: 723793 # serial number du hub
    left_wheel_stepper: 0   # hub phidget du stepper gauche
    right_wheel_stepper: 1   # hub phidget du stepper droit
    entraxe: 18.44  # en cm
    wheel_radius: 4.06 # en cm
    step_count: 200 # steps
    stop_topic: "stop_all"
    speed_factor: "speed_factor"
    tics_per_step: 32 # de combien augmente le compteur (du moteur) de position phidget par steps
    encoder_tics_count: 1200 # nombre de tics sur l'encodeur HKT22
    left_wheel_encoder: 2   # hub phidget de l'encodeur gauche
    right_wheel_encoder: 3   # hub phidget de l'encodeur droit
    odom_period : 0.25  # (en s) période de rafraichissement de l'odométrie
    x_depart: 1.0
    y_depart: 0.2
    angle_depart: 1.57
    is_left_side: True
    use_odom: False
    trajectory_goal_error: 0.1

    trajectoires:
        - [[1, 0.5, 0.2], [1, 0.5, 0.7], [-1, 1, 0.7], [-1, 1, 0.2]] # square
        - [[1, 0.5, 0.2], [1, 0.75, 0.7], [-1, 1, 0.2]] # triangle
